import { Comforter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from '@/components/Footer'

const comforter = Comforter({
  variable: "--font-comforter-sans",
  subsets: ["latin"],
  display: 'swap',
  weight: '400'
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <body>
        <Nav></Nav>
        <div className="container">{children}</div>
        <Footer year='2026' />
      </body>
    </html>
  );
}